### ISSUE TITLE
 GeneMarkS

### ISSUE THREAD

**Issue by dionizijefa** [vanya-antonov/genetack#1]
How is GeneTack useable without GeneMarkS to produce HMM files?

**Comment by vanya-antonov** [comment]
Hello dionizijefa,

Yes, you are right! GeneTack-GM requires GeneMarkS (this is GM stands for) to produce the HMM files.

At the same time, if you already have a model (in the the custom .hmm_def format https://github.com/vanya-antonov/genetack/blob/master/examples/model.hmm_def ) you don't need GeneMarkS and can run the GeneTack with this model.
